### ISSUE TITLE
[WarnSystem] Performance issues related to Regex

### ISSUE THREAD

**Issue by laggron42** [retke/Laggrons-Dumb-Cogs#125]
### Source of the problem

- [ ] InstantCommands
- [ ] RoleInvite
- [ ] Say
- [x] WarnSystem
- [ ] Other

### Description

So, Trusty reported me that WarnSystem caused issues on large bots, including crashes (more specifically Flare and Kenny's bots) because of user-settable Regex for automod (see reDOS).

I need to quickly fix this problem, the cog should be made and accessible to bots of any scale. I'm leaving this here so I don't forget.

**Comment by flaree** [comment]
I just wanna see this doesn't affect my bot as nobody has set any regexes but yeah still an issue

**Comment by TrustyJAID** [comment]
Flare is correct, while I was investigating issues on some of the larger bots I happened to come across this issue with warnsystem's regex searching. They don't appear to be related, however this is still an issue.
