### ISSUE TITLE
[WarnSystem] Remove Individual Warnings

### ISSUE THREAD

**Issue by LillyCosmo** [retke/Laggrons-Dumb-Cogs#131]
# Feature request

Cog: WarnSystem

## Description

Add a command to remove an individual warning, as I cannot find a way to, I found out how to remove all warnings with the warnings command though, just not individual.

**Comment by laggron42** [comment]
Using the `[p]warnings` command, you need to scroll to the warning you want to delete using the arrows, then click on the 🗑 reaction, this will delete the selected warning only.
