### ISSUE TITLE
[Say] saym command does not account for the mention all roles permission

### ISSUE THREAD

**Issue by Olaroll** [retke/Laggrons-Dumb-Cogs#138]
### Source of the problem

- [ ] InstantCommands
- [ ] RoleInvite
- [x] Say
- [ ] WarnSystem
- [ ] Other

### Description

Unable to mention a role when the bot should be able to do so thanks to the mention all roles permission. 
(Unless I'm missing something?)

### Steps to reproduce

1. Make the bot have the `Mention @everyone, @here, and All Roles` permission, **without** having the `Administrator` permission
2. Make a test_role **without** the `Allow anyone to mention this role` setting
3. Try to use `[p]saym @test_role`
4. The bot will say it can't mention @test_role because it doesn't have the required permissions

### Expected behaviour

Because of the `Mention all roles` permission, the mention should be sent

### Redbot context

Discord.py's version: 1.5.1

Red-DiscordBot last commit: Dunno what this means, but red's version is 3.4.5

Your cog's version: 1.5.0 (latest)

**Comment by cag1585** [comment]
I ran into the same issue. Bot with Mention All Roles permissions can not mention an unmentionable role unless the bot has Admin permission.

**Comment by laggron42** [comment]
Forgot to close this, but this was fixed in [d7975e2](https://github.com/laggron42/Laggrons-Dumb-Cogs/commit/d7975e290c87f6328b736b9f2e899f8c8d6a39d9), you can update and this should work fine.
