### ISSUE TITLE
[Say] Interact can send message but can't receive

### ISSUE THREAD

**Issue by Zenchaeus** [retke/Laggrons-Dumb-Cogs#149]
### Source of the problem
interact command
Cog: Say

### Description
when i use the interact command, i can send a message through my bot to a specific channel i choose. but when someone sends a message to that channel, i can't receive it through my bot.
### Redbot context

Discord.py's version: 1.6.0

Red-DiscordBot's version: 3.4.7

Your cog's version: 1.5.0

**Comment by laggron42** [comment]
Works for me, can't reproduce.

The bot will ignore messages sent by the user of this command (so don't bother sending messages yourself, ask someone else to test with you).

Please confirm that the messages not forwarded to you are *not* your own messages.

**Comment by Zenchaeus** [comment]
> Works for me, can't reproduce.
> 
> The bot will ignore messages sent by the user of this command (so don't bother sending messages yourself, ask someone else to test with you).
> 
> Please confirm that the messages not forwarded to you are _not_ your own messages.

yeah that is the case. i tried with another account and it does work for others but not with my own. thanks for the info
