### ISSUE TITLE
RuntimeWarning: coroutine 'GuildChannel.set_permissions' was never awaited channel.set_permissions

### ISSUE THREAD

**Issue by Skyridr** [retke/Laggrons-Dumb-Cogs#170]
Merely wanted to forward what I noticed in the logs:

```py
warnsystem.py:1363: RuntimeWarning: coroutine 'GuildChannel.set_permissions' was never awaited channel.set_permissions(
```

```py
        try:
            channel.set_permissions(
                role,
                send_messages=False,
                add_reactions=False,
                reason=_(
                    "Updating channel settings so the mute role will work here. "
                    "Disable the auto-update with [p]warnset autoupdate"
                ),
            )
```

Assuming it's referring to await missing? -> await channel.set_permissions(.

**Comment by laggron42** [comment]
That was fixed a month ago with #165, update and it should work.

If your repo is broken and you can't update to version 1.3.18 (check with `[p]warnsysteminfo`), do the following:

1. `[p]unload warnsystem`
2. `[p]cog uninstall <laggron-repo> warnsystem`
3. `[p]repo remove <laggron-repo>` 
4. `[p]repo add <laggron-repo> https://github.com/retke/Laggrons-Dumb-Cogs.git`
5. `[p]cog install <laggron-repo> warnsystem`
6. `[p]load warnsystem`

Replace `<laggron-repo>` by how you named the repo. Data is kept.
