### ISSUE TITLE
[WarnSystem] Defender/Warden Integration

### ISSUE THREAD

**Issue by EternalllZM** [retke/Laggrons-Dumb-Cogs#181]
# Feature request

Cog: WarnSystem

## Description

I would love to see this cog integrate and interface with Defender's Warden module. As it stands currently, you must use the `issue-command` action in order to integrate this, as `ban-user` and other actions requiring the _mod_ cog do not register with it.

**Comment by laggron42** [comment]
Twentysix's Defender only gives informations to other cogs when an action is committed (like emergency mode engaged or member removed). It's not made to allow other cogs to add their own actions to the system, or would require heavy monkeypatching, which would made the cog unstable.

I don't think Twentysix plans to allow other cogs to interact with Defender's warden, and making a fork would make a lot of stuff hard to manage on the 3rd party cog support server.

Closing this for now, if there's an official way to do this, feel free to reopen.
