### ISSUE TITLE
Does not support line breaks

### ISSUE THREAD

**Issue by dannymichel** [retke/Laggrons-Dumb-Cogs#187]
This cog does not support line breaks

**Comment by Jackenmen** [comment]
What cog? You completely disregarded the issue template and have not provided enough information

**Comment by dannymichel** [comment]
> What cog? You completely disregarded the issue template and have not provided enough information

the ``.say`` cog

**Comment by laggron42** [comment]
Works as far as I know.

![image](https://user-images.githubusercontent.com/23153234/147659466-88e6c65c-6812-4e12-8fcb-6ad975492b99.png)

If this issue still occurs, please create a new issue using the templates, and add more details.
