### ISSUE TITLE
.saym default

### ISSUE THREAD

**Issue by dannymichel** [retke/Laggrons-Dumb-Cogs#188]
I believe .saym should be default.

**Comment by ltzmax** [comment]
I don't see what's hard with one extra letter to type.. you know It's not hard to type an extra letter, just add an `m` after `say`. 🤷

**Comment by laggron42** [comment]
This extra step (or letter) is done on purpose, so people can truely specify whether they want the bot ping the people or not, and it's not the default to prevent accidental massive pings.

If you have more suggestions, please use the provided issue template.
