### ISSUE TITLE
Typo in variable name - bettermod.py

### ISSUE THREAD

**Issue by Soulrift** [retke/Laggrons-Dumb-Cogs#19]
bettermod.py:Line 318:
         `   l_channel_embed_softban = 'None' if 'softban_warn' in setting['channels'] is False else setting['channels']['softban_warn']`

both instances of softban_warn should be softban-warn;  this is how they're initialized in the settings data structure.

This should fix any remaining crashes

**Comment by retke** [comment]
Fixed by #20
