### ISSUE TITLE
New command

### ISSUE THREAD

**Issue by DairyWeb3638077** [retke/Laggrons-Dumb-Cogs#194]
### Type of feature request

Command

### The cog your feature request is for.

InstantCommands

### Description of the feature you're suggesting

Can you please add a feature to edit already existing commands? It is frustrating having to copy the source of a command, delete the command, create a new one just to make a small change.

**Comment by laggron42** [comment]
You can add the same command again and the bot will detect that it has the same name as an existing command. It will then ask if you want to overwrite or cancel.

Basically, commands don't have a key, it's stored as a list of code blocks, so an edit command would have the exact same behavior and usage as the add command.

**Comment by DairyWeb3638077** [comment]
oh ok. Thank you so much.
