### ISSUE TITLE
WarnSystem - [p]set modrole and [p]set adminrole do nothing

### ISSUE THREAD

**Issue by WildFyr16** [retke/Laggrons-Dumb-Cogs#218]
### Red's version

3.5.13

### The cog you're using.

WarnSystem

### The cog's version

1.5.6

### The command you're using

set modrole

### What did you expect to happen?

It to set a role allowed to use the [p]warn command

### What actually happened?

Nothing other then the Help submenu for the [p]set command, I do not see a "modrole" or "adminrole" in the list.

### How can we reproduce this error?

1. Install the COG
2. Run the [p]set modrole <role>
3. Nothing happens

**Comment by Flame442** [comment]
Red 3.5 changed the syntax for `[p]set modrole` to instead be `[p]set roles addmodrole` and `addadminrole` respectively. If WarnSystem is suggesting users use the pre 3.5 command syntax, it will need to be updated with the new syntax.

**Comment by laggron42** [comment]
Oh that's correct, I missed on documenting this

**Comment by laggron42** [comment]
The only place where I found an occurence of `[p]set modrole` instead of `addmodrole` was the documentation, feel free to comment if I missed somewhere
