### ISSUE TITLE
Add Timed Mute/Punish to Bettermod

### ISSUE THREAD

**Issue by tbstewa** [retke/Laggrons-Dumb-Cogs#28]
## Type

- [X] Addition
- [ ] New cog

### Cog

- [ ] RoleInvite
- [ ] Say
- [X] Bettermod

## Description
I would like to see bettermod have a function similar to a mute/punishment cog as well. That way, I'm not punishing users and then giving them a warning via bmod. The current cog I'm using for punishments is one that Kowlin made, but I adjusted it for my servers.

**Comment by retke** [comment]
V2 is currently feature locked. I might do this when I'll have time, but this is not the priority. This should be there if there's a V3 port of BetterMod tho.

I'll freeze this for now, this might exist one day, but I do not guarantee that.

**Comment by retke** [comment]
V3 has this function and V2 cogs are no longer supported. If you want to see this, consider upgrading to V3 and installing the warnsystem cog, there is even a data converter tool if you want to keep your logs.
