### ISSUE TITLE
Say is not working on V3.0.0b20

### ISSUE THREAD

**Issue by pabloleban** [retke/Laggrons-Dumb-Cogs#29]
### Source of the problem

- [x] Say
- [ ] RoleInvite
- [ ] Other

### Description

Say throws an error when loading on 3.0.0b20

### Steps to reproduce

1. Load cog on V3 last version

2. You get this:

```
[31/08/2018 20:17] ERROR core_commands _load 97: Package loading failed
Traceback (most recent call last):
  File "/root/.local/lib/python3.7/site-packages/redbot/core/core_commands.py", line 95, in _load
    await bot.load_extension(spec)
  File "/root/.local/lib/python3.7/site-packages/redbot/core/bot.py", line 228, in load_extension
    lib.setup(self)
  File "/root/obesin/cogs/CogManager/cogs/say/__init__.py", line 21, in setup
    n = Say(bot)
  File "/root/obesin/cogs/CogManager/cogs/say/say.py", line 39, in __init__
    if bot.loop.create_task(bot.db.enable_sentry()):
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 386, in create_task
    task = tasks.Task(coro, loop=self)
TypeError: a coroutine was expected, got <redbot.core.config._ValueCtxManager object at 0x7f2780e326a0>
```

**Comment by retke** [comment]
Cannot reproduce this on my end. Can you please give me the following informations:

- Python version: `python3 --version` in a shell/cmd
- Red version: `[p]info` or `redbot --version` in a shell/cmd
- Say version: `[p]sayinfo`

**Comment by retke** [comment]
Try to uninstall the cog and the repo. Install them back and load the cog. Dunno if this will fix it, but since there is no way to know the version, we'll have to make sure it's the latest version.

**Comment by pabloleban** [comment]
I have reinstalled it. Still getting the same result.

![image](https://user-images.githubusercontent.com/13904174/45322756-9698a580-b51f-11e8-9fae-d17dd2e3f4c9.png)

**Comment by pabloleban** [comment]
I've also updated to b21 and still getting the same error.
![image](https://user-images.githubusercontent.com/13904174/45322987-37876080-b520-11e8-8729-478c7b922c26.png)

**Comment by retke** [comment]
Still can't reproduce it, I'm looking for a fix with Red's devs, please hold on, we may need more informations. If this get fixed, you'll be notified.

**Comment by retke** [comment]
Alright, after some tests, I noticed this error only happens with Python 3.7.0. This issue is linked to [asyncio's 3.7 breaking changes](https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-asyncio) and should be fixed by rewriting the Sentry logging selection. This should be done during the week.

**Comment by retke** [comment]
Okay, I pushed Say 1.4.5 which modifies how Sentry logging is handheld, which will also fix this error. Didn't have time to test it for long, but this should be fine. Just update the cog and let me know if this works!

**Comment by pabloleban** [comment]
Works great.
