### ISSUE TITLE
warnsystem not show mod

### ISSUE THREAD

**Issue by entchen66** [retke/Laggrons-Dumb-Cogs#38]
### Source of the problem

- [ ] Say
- [ ] RoleInvite
- [x] Other

### Description

[p]warnset showmod did not work in a correct way. I didn't change any setting. You can see it on the screenshoot.

### Steps to reproduce

![grafik](https://user-images.githubusercontent.com/1564726/51979560-bceabd80-248d-11e9-9952-179a4aaae835.png)

### Redbot context

Discord.py's version: 1.0.0a

Red-DiscordBot last commit: 3.0.0

Your cog's version: 1.0.1

**Comment by retke** [comment]
This was fixed with 34e17dde8cd65a237328038d792270243aa3a9d2, thanks for reporting the error.
The patch is on the beta branch right now and should be merged to the stable branch before the end of the week, I'll keep this open until that is done.
