### ISSUE TITLE
WarnSystem small debug word mistype

### ISSUE THREAD

**Issue by Skyrid3r** [retke/Laggrons-Dumb-Cogs#46]
Just something I noticed, nothing big but wanted to mention it:

`[08/05/2019 00:21] DEBUG WarnSystem: Starting infinite loop for unmutes and unbans. Canel the task with bot.get_cog("WarnSystem").task.cancel()`

"Canel" -> Cancel

**Comment by retke** [comment]
Thanks for noticing this, I'm gonna fix it for #44 !
