### ISSUE TITLE
[enhancement request] Simplify Level 1 warning

### ISSUE THREAD

**Issue by Skyrid3r** [retke/Laggrons-Dumb-Cogs#47]
I really love the cog and the ability to log things, even if the user is no longer on the server. Though I was hoping you could include the small enhancement to simplify warnings based on level 1 (simple warning)

Rather than:

`[p]warn 1 @userID reason`

Would be nice to have:

`[p]warn @userID reason`

Seeing level 1 is only a warning alone and which is quite often used, it would be a bit quicker to warn the user. If no level is provided, it would by default use level 1.

**Comment by Dezyox** [comment]
Better than this
A setting for the owner to set what to do when no option are given, like :

`[p]warnset nolevel <Level of the moderation>`

So, if it's 1, only using `[p]warn ...` will warn the user
If it's 2, only using `[p]warn ...`will mute the user
...

Hope it can be added, but I think it can be a little useless for some users...

**Comment by retke** [comment]
Uh, I already coded what you asked at first for 1.1 version, so maybe for next update...
