### ISSUE TITLE
[Feature Request] Show all warned users using eg [p]warnlist

### ISSUE THREAD

**Issue by Skyrid3r** [retke/Laggrons-Dumb-Cogs#48]
By default, the warnings command gives you the ability to view warnings of a specific user. Though it would be nice to view all names of people that has been warned with the amount of mutes/warnings/kicks, etc listed.

EG:

| [USERNAME]  | [WARNINGS] | [KICKS] | [BANNED] | [MUTED] |
|-------------|------------|---------|----------|---------|
| [Skyrider1] | [6x]       | [1x]    | [1x]     | [3x]    |
| [Skyrider2] | [4x]       | [0x]    | [0x]     | [1x]    |
| [Skyrider3] | [2x]       | [0x]    | [0x]     | [0x]    |

Merely an example, so the overview can be done a lot better. But it would be nice to have a list command to view them all at once.

**Comment by laggron42** [comment]
I'm not planning any leaderboard or table function for now.
