### ISSUE TITLE
Punish 1 (warn) doesn't respect hierarchy 

### ISSUE THREAD

**Issue by Skyrid3r** [retke/Laggrons-Dumb-Cogs#53]
Apparently you can still warn other mods/admins, it's not respecting the hierarchy while kick/ban does.

**Comment by retke** [comment]
The bot doesn't check the permissions for level 1 warns since it doesn't take any actions, unlike the others levels where Discord rules requires the bot to have a higher role. However, the hierarchy check between the warned member and the moderator will not exclude the level 1 warning.

**Comment by Skyrid3r** [comment]
Any specific reason though? Mods/Admins can "warn" other mods/admins. Even though no actual action is being taken besides being logged, it's still silly it's possible.
