### ISSUE TITLE
Punishing people in hierarchy still shows "succeeded"

### ISSUE THREAD

**Issue by Skyrid3r** [retke/Laggrons-Dumb-Cogs#55]
Apparently whenever you attempt to kick/ban someone in hierarchy, it shows a green reaction telling it succeeded?

![image](https://user-images.githubusercontent.com/6794064/60828856-d66a0100-a1b3-11e9-9c65-212aa72c0dbf.png)

Maybe it should show a red cross meaning it failed, for any reason.

**Comment by retke** [comment]
Already planned for version 1.1, see #44
