### ISSUE TITLE
WarnSystem don't reinvite a user when he is unbanned

### ISSUE THREAD

**Issue by Dezyox** [retke/Laggrons-Dumb-Cogs#58]
### Source of the problem

- [  ] InstantCommands
- [  ] RoleInvite
- [  ] Say
- [x] WarnSystem
- [  ] Other

### Description

When you unban a user, normally, WarnSystem send a invitation back to the user, but he don't

### Steps to reproduce

1. Ban someone
2. Unban him

### Expected behaviour

The bot don't send the invitation to the user after being unbanned

### Redbot context

Discord.py's version: Discord.py 1.2.3

Red-DiscordBot last commit: 3.1.5

Your cog's version: WarnSystem 1.1.2

### Additional context

The bot share a another server with the user I unbanned.
The bot have reinvite toggled.

**Comment by retke** [comment]
WarnSystem will only send a DM to members unbanned by WarnSystem (once the temporary ban ends). A manual unban will only remove him from the list of temporary warns and will not send a DM *yet*. You can still suggest this for an update.

**Comment by Dezyox** [comment]
I will, thank
