### ISSUE TITLE
[WarnSystem] Reinvite in any way

### ISSUE THREAD

**Issue by Dezyox** [retke/Laggrons-Dumb-Cogs#59]
# Feature request for WarnSystem

## Description

If reinvite has been activated, and the user has been unbanned from the guild, like unbanning the user from the server settings, reinvite the user instead of just reinviting the user with a temporary ban

**Comment by laggron42** [comment]
With the `[p]wsunban` command this is now doable, and I don't want to make something automated for manual bans, this could be pretty annoying in some cases.
