### ISSUE TITLE
[InstantCMD] Created commands cause [p]findcog to error

### ISSUE THREAD

**Issue by Flame442** [retke/Laggrons-Dumb-Cogs#61]
### Source of the problem

- [x] InstantCommands
- [ ] RoleInvite
- [ ] Say
- [ ] WarnSystem
- [ ] Other

### Description

Attempting to run `[p]findcog <command>` where "command" is a command created with InstantCMD causes the following error:
```py
Exception in command 'findcog'
Traceback (most recent call last):
  File "redbot\cogs\downloader\downloader.py", line 593, in findcog
    cog_name = self.cog_name_from_instance(command.cog)
  File "redbot\cogs\downloader\downloader.py", line 577, in cog_name_from_instance
    splitted = instance.__module__.split(".")
AttributeError: 'NoneType' object has no attribute '__module__'
```

### Steps to reproduce

1. Run `[p]instantcmd create`
2. Enter any command (simple example command below)
```py
@commands.command()
async def testcmd(ctx):
    await ctx.send("Hello!")

return testcmd
```
3. Run `[p]findcog <command>` where "command" is the command you just made

### Expected behaviour

Not an error, this should be handled in some way that you see fit.

### Redbot context

Discord.py's version: 1.2.3

Red-DiscordBot 's version: 3.1.5

Your cog's version: See #62

**Comment by laggron42** [comment]
Bug on Red's end.
Issue: https://github.com/Cog-Creators/Red-DiscordBot/issues/2902
PR: https://github.com/Cog-Creators/Red-DiscordBot/pull/2970

**Comment by laggron42** [comment]
https://github.com/Cog-Creators/Red-DiscordBot/pull/2970 was merged *a pretty long time ago*, can close.
