### ISSUE TITLE
Mute also on Voice Channels

### ISSUE THREAD

**Issue by Bartixxx32** [retke/Laggrons-Dumb-Cogs#74]
# Feature request

Cog: warnsystem

## Description

Make cog muting users on voice channels too

**Comment by Menteroth** [comment]
![image](https://user-images.githubusercontent.com/24851042/80321611-baa51980-881e-11ea-8ea6-9b2dbb833263.png)

**Comment by laggron42** [comment]
👍 Will do for 1.3
