### ISSUE TITLE
[p]automod antispam does not work properly (does not take any action)

### ISSUE THREAD

**Issue by Skyridr** [retke/Laggrons-Dumb-Cogs#82]
See: https://github.com/retke/Laggrons-Dumb-Cogs/issues/86

Reason why it wasn't working is because of mute being broken. Though, automod also started breaking after this: 

https://github.com/retke/Laggrons-Dumb-Cogs/issues/85

**Comment by laggron42** [comment]
Both of the mentioned issues are resolved. Consider updating this by either closing if this is fixed, or providing more details (check `warnsystem.log`).

**Comment by laggron42** [comment]
Can't reproduce, code changed much since then, I feel like this issue is outdated now. Feel free to repoen if necessary.
