### ISSUE TITLE
[bug?] Automod does not DM the user when action is taken against them.

### ISSUE THREAD

**Issue by Skyridr** [retke/Laggrons-Dumb-Cogs#83]
Not sure if this a bug or a missing feature. But when using automod and an action has been taken against the user, it's logging its actions nicely within the set channel. But it does not DM the user at all like it would when you take action against a user yourself.

Can this be included/added?

**Comment by laggron42** [comment]
Can confirm this is an acutal issue that affects all warnings, not only automod. I'm just a dumb guy who forgot to remove debug code.
