### ISSUE TITLE
[Feature Request] Prune Member Warning logs log

### ISSUE THREAD

**Issue by Skyridr** [retke/Laggrons-Dumb-Cogs#88]
Noticed the lovely feature that gives you the ability to erase all warnings on a specific member. Would be nice however, if this would be logged if this action was used on someone. Maybe in an embed with all previous warnings / actions of the user for just in case scenarios. , and or saved in a txt file.

**Comment by laggron42** [comment]
Right now this is logged in `warnsystem.log`. This is obviously not comparable with logging in a Discord channel, but still provides a way to track things if really needed. And I'm not fond of this idea of logging a general deletion, sorry.
