### ISSUE TITLE
Clearing a user warn history, does not clear their mute role (if any)

### ISSUE THREAD

**Issue by Skyridr** [retke/Laggrons-Dumb-Cogs#95]
Noticed today that when you erase a users entire modlog and the user is still muted by the warnsystem, it's not removing the muted role.

**Comment by laggron42** [comment]
This is intended, the sole thing this function does is removing anything saved for this user. Running the same checks and actions as a simple deletion for each warning in the modlog would be incredibly expensive in resources.

**Comment by Skyridr** [comment]
Wouldn't it only include a few code lines to "check" if the user has a muted role in place and remove if it it does?

- Has mute role? -> Remove
- No mute role? -> Ignore

As you'd clear the entire user warn history, so should it (at least in my opinion) erase the users mute (if any).
